version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.2.0
  - dependency-name: chromedriver
    versions:
    - 87.0.4
    - 88.0.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: vue-router
    versions:
    - 3.5.0
